final products = [
  {
    'id': '1',
    'title': 'Men\'s 1st Nike Shoes',
    'price': 44.52,
    'imageUrl': 'assets/images/nike-shoe-1.jpeg',
    'company': 'Nike',
    'sizes': [7, 8, 9, 10, 11, 12],
  },
  {
    'id': '2',
    'title': 'Men\'s 2nd Nike Shoes',
    'price': 102.32,
    'imageUrl': 'assets/images/nike-shoe-2.jpeg',
    'company': 'Nike',
    'sizes': [7, 9, 10, 11, 12],
  },
  {
    'id': '3',
    'title': 'Men\'s 1st Adidas Shoes',
    'price': 143.53,
    'imageUrl': 'assets/images/adidas-shoe-1.jpeg',
    'company': 'Adidas',
    'sizes': [6, 7, 8, 9, 10, 11, 12],
  },
  {
    'id': '4',
    'title': 'Men\'s 2nd Adidas Shoes',
    'price': 148.93,
    'imageUrl': 'assets/images/adidas-shoe-2.jpg',
    'company': 'Adidas',
    'sizes': [6, 7, 8, 9, 10, 11, 12, 13],
  },
  {
    'id': '5',
    'title': 'Men\'s Reebok Shoes',
    'price': 77.89,
    'imageUrl': 'assets/images/reebok-shoe-1.jpg',
    'company': 'Reebok',
    'sizes': [7, 8, 9, 10, 11, 12],
  },
];
